[package]
name = "desktus"
version = "0.4.0"
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
edition = "2018"
description = "Desktop status bar client for i3bar and swaybar"
license = "Zlib"
homepage = "https://github.com/stephaneyfx/desktus"
repository = "https://github.com/stephaneyfx/desktus.git"
keywords = ["status", "bar", "i3bar", "i3"]

[dependencies]
battery = "0.7.8"
chrono = "0.4.19"
futures = "0.3.13"
heim = "0.0.11"
number_prefix = "0.4.0"
palette = "0.5.0"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.2.0", features = ["full"] }
