[package]
name = "desktus"
version = "0.4.0"
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
edition = "2018"
description = "Desktop status bar client for i3bar and swaybar"
license = "MIT"
homepage = "https://github.com/stephaneyfx/desktus"
repository = "https://github.com/stephaneyfx/desktus.git"
keywords = ["status", "bar", "i3bar", "i3"]

[dependencies]
battery = "0.7.8"
chrono = "0.4.19"
futures = "0.3.12"
heim = "0.0.11"
palette = "0.5.0"
serde_json = "1.0.61"

[dependencies.async-ctrlc]
version = "1.2.0"
features = ["termination"]

[dependencies.async-std]
version = "1.9.0"
features = ["unstable"]

[dependencies.serde]
version = "1.0.120"
features = ["derive"]
