[package]
name = "desktus"
version = "0.3.0"
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
edition = "2018"
description = "Desktop status bar client for i3bar"
license = "MIT"
homepage = "https://github.com/stephaneyfx/desktus"
repository = "https://github.com/stephaneyfx/desktus.git"
keywords = ["status", "bar", "i3bar", "i3"]

[dependencies]
battery = "0.7.5"
chrono = "0.4.10"
futures = "0.3.1"
rgb = "0.8.14"
serde_json = "1.0.44"

[dependencies.async-ctrlc]
version = "1.0.0"
features = ["termination"]

[dependencies.async-std]
version = "1.4.0"
features = ["unstable"]

[dependencies.serde]
version = "1.0.104"
features = ["derive"]
