[package]
name = "desktus"
version = "0.1.0"
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
edition = "2018"
description = "Desktop status bar client for i3bar"
license = "MIT"
homepage = "https://github.com/stephaneyfx/desktus"
repository = "https://github.com/stephaneyfx/desktus.git"
keywords = ["status", "bar", "i3bar", "i3"]

[dependencies]
chrono = "0.4.7"
rgb = "0.8.13"
serde_json = "1.0.39"

[dependencies.ctrlc]
version = "3.1.3"
features = ["termination"]

[dependencies.serde]
version = "1.0.94"
features = ["derive"]
